[package]
name = "noc-rust"
version = "0.1.0"
authors = ["Dominic Lee <dominictwlee@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.14"
rand = "0.5"
perlin_noise = "1.0.1"
